
version: '3.8'

services:
  busybox:
    image: busybox:latest
    secrets:
      - source: app_secret
        target: /run/secrets/busybox


secrets:
  app_secret:
    driver: docker-plugin-secrets
#    labels:
#      docker.plugin.secretprovider.vault.path: canux/db/data/db
#      docker.plugin.secretprovider.vault.field: rw
