
#version: '3.8'

services:
  nginx:
    image: nginx


#volumes:
#  busybox_secret:
#    driver: secret_template_volume
#    driver_opts:
#      url: "s3://xxxx?path="
#      template-dir: './xxx'
#
#secrets:
#  app_secret:
#    environment: 'ignore'               # ignore
#    template-driver: docker-plugin-secrets
#    labels:
#      docker.plugin.secretprovider.vault.path: canux/db/data/db
#      docker.plugin.secretprovider.vault.field: rw
